version: 2
updates:
  # Example 1: For Python (pip)
  - package-ecosystem: "pip"
    directory: "/"  # Root directory where `requirements.txt` is located
    schedule:
      interval: "weekly"

  # Example 2: For Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"  # Root directory where `package.json` is located
    schedule:
      interval: "weekly"

  # Example 3: For GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of .github/workflows/
    schedule:
      interval: "weekly"
