name: OWASP ZAP Automated Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # Runs every Monday at 3 AM UTC

permissions:
  issues: write
  contents: read
  security-events: write  # Required for uploading security reports

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OWASP ZAP (If Not Installed)
        run: |
          sudo apt update
          sudo apt install zaproxy -y

      - name: Create Directory for Reports
        run: mkdir -p zap_reports

      - name: Generate Unique Report Name
        run: |
          INDEX=$(ls zap_reports | wc -l)
          REPORT_NAME="zap_report_$((INDEX+1)).html"
          echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_ENV

      - name: Run OWASP ZAP Scan and Save as HTML
        run: |
          zap.sh -cmd -quickurl "http://3.80.13.217/DVWA" -quickprogress -r "zap_reports/${REPORT_NAME}"

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4  
        with:
          name: "${{ env.REPORT_NAME }}"
          path: "zap_reports/${{ env.REPORT_NAME }}"

      - name: List Saved Reports (Debugging)
        run: ls -lh zap_reports/

      - name: Print Success Message
        run: echo "ZAP scan completed. The report is saved as ${{ env.REPORT_NAME }} and uploaded as an artifact."
