name: OWASP ZAP Automated Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # Runs every Monday at 3 AM UTC
permissions:
  issues: write
  contents: read
  security-events: write
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://3.80.13.217/DVWA'
          allow_issue_writing: false
          cmd_options: '-a'
          
      - name: Format Date for Report Name
        id: date
        run: echo "report_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Create Reports Directory
        run: |
          mkdir -p security-reports
          cp zap-baseline.html "security-reports/zap-scan-report-${{ steps.date.outputs.report_date }}.html"
          cp zap-baseline.md "security-reports/zap-scan-report-${{ steps.date.outputs.report_date }}.md"
          cp zap-baseline.json "security-reports/zap-scan-report-${{ steps.date.outputs.report_date }}.json"
          
      - name: Create Index HTML
        run: |
          echo "<!DOCTYPE html>" > security-reports/index.html
          echo "<html lang='en'>" >> security-reports/index.html
          echo "<head>" >> security-reports/index.html
          echo "  <meta charset='UTF-8'>" >> security-reports/index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> security-reports/index.html
          echo "  <title>OWASP ZAP Security Reports</title>" >> security-reports/index.html
          echo "  <style>" >> security-reports/index.html
          echo "    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }" >> security-reports/index.html
          echo "    h1 { color: #333; }" >> security-reports/index.html
          echo "    .report-link { display: block; margin: 10px 0; padding: 10px; background-color: #f5f5f5; border-radius: 5px; text-decoration: none; color: #333; }" >> security-reports/index.html
          echo "    .report-link:hover { background-color: #e0e0e0; }" >> security-reports/index.html
          echo "  </style>" >> security-reports/index.html
          echo "</head>" >> security-reports/index.html
          echo "<body>" >> security-reports/index.html
          echo "  <h1>OWASP ZAP Security Scan Reports</h1>" >> security-reports/index.html
          echo "  <p>Latest scan completed on: ${{ steps.date.outputs.report_date }}</p>" >> security-reports/index.html
          echo "  <h2>Available Reports:</h2>" >> security-reports/index.html
          echo "  <a class='report-link' href='zap-scan-report-${{ steps.date.outputs.report_date }}.html'>HTML Report (${{ steps.date.outputs.report_date }})</a>" >> security-reports/index.html
          echo "  <a class='report-link' href='zap-scan-report-${{ steps.date.outputs.report_date }}.md'>Markdown Report (${{ steps.date.outputs.report_date }})</a>" >> security-reports/index.html
          echo "  <a class='report-link' href='zap-scan-report-${{ steps.date.outputs.report_date }}.json'>JSON Report (${{ steps.date.outputs.report_date }})</a>" >> security-reports/index.html
          echo "</body>" >> security-reports/index.html
          echo "</html>" >> security-reports/index.html
      
      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report-${{ steps.date.outputs.report_date }}
          path: security-reports/
          retention-days: 90
